project_id = "hkckgwptmycyebrcffxk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-confirmation]
verify_jwt = true

[functions.send-campaign-pdf]
verify_jwt = true

[functions.create-agent-user]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.abandoned-cart-reminder]
verify_jwt = false